authentication/urls.py
from django.urls import path

from authentication.views import RegisterAPIView, LoginAPIView, AuthenticationTemplateView

app_name = "authentication"

urlpatterns = [
    path('', AuthenticationTemplateView.as_view(), name="authentication"),

    path('login/', LoginAPIView.as_view(), name="login"),
    path('register/', RegisterAPIView.as_view(), name="register"),

]

game/urls.py
from django.urls import path

from game.views.answer_question_apiview import AnswerQuestionAPIView
from game.views.home_templateview import HomeTemplateView
from game.views.initial_game_apiview import InitialGameAPIView
from game.views.top_players_retreive_view import TopPlayersListAPIView
from game.views.game_initial_templateview import GameInitialTemplateView

app_name = "game"

urlpatterns = [
    path('answer/<str:game_uuid>/', AnswerQuestionAPIView.as_view(), name="answer"),
    path('initial/', InitialGameAPIView.as_view(), name="initial"),
    path('top-players/', TopPlayersListAPIView.as_view(), name="top-players"),

    path('home/', HomeTemplateView.as_view(), name="home"),
    path('game-initial/', GameInitialTemplateView.as_view(), name="initial-template"),
]

millionaire/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include("game.urls", namespace="game")),
    path('authentication/', include("authentication.urls", namespace="authentication")),
    path('', RedirectView.as_view(url="/authentication/", )),

]

authentication/models.py
from django.db import models

# Create your models here.

game/models/game.py
from uuid import uuid4

from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from django.db import models


class Game(models.Model):
    uuid = models.CharField(
        verbose_name=_("uuid"),
        max_length=64,
        default=uuid4
    )
    user = models.ForeignKey(
        User,
        verbose_name=_("user"),
        related_name="games",
        on_delete=models.CASCADE
    )
    questions = models.ManyToManyField(
        "game.Question",
        verbose_name=_("questions"),
        related_name="games"
    )
    total_score = models.PositiveIntegerField(
        verbose_name=_("total_score"),
        default=0
    )

    class Meta:
        verbose_name = "game"
        verbose_name_plural = "games"

    def __str__(self):
        return f"{self.user.username} / {self.uuid}"

game/models/option.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _


class Option(models.Model):
    text = models.TextField(
        verbose_name=_("text"),
        max_length=1024,
    )
    is_correct = models.BooleanField(
        default=False,
        verbose_name=_("is_correct")
    )
    question = models.ForeignKey(
        "game.Question",
        verbose_name=_("question"),
        related_name="options",
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "option"
        verbose_name_plural = "options"

    def __str__(self):
        return f"{self.text[:50]} / {str(self.is_correct)}"

game/models/question.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class Question(models.Model):
    text = models.TextField(
        verbose_name=_("text"),
        max_length=2056,
    )
    score = models.PositiveIntegerField(
        default=5,
        validators=[MinValueValidator(5), MaxValueValidator(20)]
    )

    class Meta:
        verbose_name = "question"
        verbose_name_plural = "questions"

    def __str__(self):
        return f"{self.text[:50]} / {str(self.score)}"

authentication/views/authentication_templateview.py
from utils.views import BaseTemplateView


class AuthenticationTemplateView(BaseTemplateView):
    template_name = "authentication/authentication.html"

authentication/views/login_apiview.py
from django.contrib.auth import authenticate, login
from rest_framework.response import Response
from rest_framework.views import APIView


class LoginAPIView(APIView):
    def post(self, request):
        username = request.data.get("username")
        password = request.data.get("password")

        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            response = Response(data={}, status=200)
            response.set_cookie("user_pass", password)  # This is SILLY!
            return response
        return Response(data={"error": "not authenticated"}, status=403)

authentication/views/register_apiview.py
from rest_framework.generics import CreateAPIView

from authentication.serializers import RegisterSerializer


class RegisterAPIView(CreateAPIView):
    serializer_class = RegisterSerializer

    def post(self, request, *args, **kwargs):
        response = super(RegisterAPIView, self).post(request, *args, **kwargs)
        response.set_cookie("user_pass", request.data["password"])  # This is SILLY!
        return response

game/views/answer_question_apiview.py
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from game.models import Game
from game.serializers import AnswerQuestionSerializer


class AnswerQuestionAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request, *args, **kwargs):
        serializer = AnswerQuestionSerializer(
            data=request.data, context={
                "game": Game.objects.filter(uuid=self.kwargs.get("game_uuid")).last()
            }
        )
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            return Response(data={"data": serializer.data}, status=200)
        return Response(data=serializer.data, status=400)

game/views/game_initial_templateview.py
from utils.views import BaseTemplateView


class GameInitialTemplateView(BaseTemplateView):
    template_name = "game/game-initial.html"

game/views/home_templateview.py
from utils.views import BaseTemplateView


class HomeTemplateView(BaseTemplateView):
    template_name = "game/home.html"

game/views/initial_game_apiview.py
from django.contrib.auth.models import User
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from game.models import Game, Question
from game.serializers import GameSerializer


class InitialGameAPIView(APIView):
    permission_classes = [IsAuthenticated]

    def post(self, request):
        questions = (
            Question.objects.order_by("?")[:5]
        )

        game = Game.objects.create(
            user=User.objects.get(username="parsa"),
        )
        for question in questions:
            game.questions.add(question)

        serializer = GameSerializer(instance=game)
        return Response(
            data={"data": serializer.data}
        )

game/views/top_players_retreive_view.py
from rest_framework.generics import ListAPIView
from rest_framework.response import Response

from game.models import Game
from game.serializers import TopPlayerSerializer


class TopPlayersListAPIView(ListAPIView):
    serializer_class = TopPlayerSerializer

    def get_queryset(self):
        return Game.objects.all().order_by("user_id", "-total_score").distinct("user_id")[:5]

    def list(self, request, *args, **kwargs):
        response = super(TopPlayersListAPIView, self).list(request, *args, **kwargs)
        return Response(data={"data": response.data})

utils/views/base_templateview.py
from django.views.generic import TemplateView


class BaseTemplateView(TemplateView):

    def get_context_data(self, **kwargs):
        context = super(BaseTemplateView, self).get_context_data(**kwargs)
        context.update({
            "user": self.request.user,
            "password": self.request.COOKIES.get("user_pass"),
            "csrftoken": self.request.COOKIES.get("csrftoken"),
        })
        return context

templates/authentication/authentication.html
{% extends 'base/base.html' %}

{% block content %}

    <div class="container">
        <div class="row ">
            <div class="col-sm-6">
                <form id="signUp">
                    <div class="mb-4" style="font-size: 18px; font-weight: 600;">SignUP</div>
                    <div class="form-group">
                        <div style="margin-bottom: 24px;">
                            <label class="mb-1" for="signupInputUsername">Username</label>
                            <input type="text" class="form-control" id="signupInputUsername"
                                   placeholder="Enter username">
                        </div>
                        <div style="margin-bottom: 24px;">
                            <label class="mb-1" for="signupInputFirstname">First Name</label>
                            <input type="text" class="form-control" id="signupInputFirstname"
                                   placeholder="Enter First Name">

                        </div>
                        <div style="margin-bottom: 24px;">
                            <label class="mb-1" for="signupInputLastname">Last Name</label>
                            <input type="text" class="form-control" id="signupInputLastname"
                                   placeholder="Enter Last Name">

                        </div>
                        <div style="margin-bottom: 24px;">
                            <label class="mb-1" for="signupInputPassword">Password</label>
                            <input type="password" class="form-control" id="signupInputPassword"
                                   placeholder="Enter Password">
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary" id="submitSignup">Submit</button>
                </form>
            </div>
            <div class="col-sm-6">
                <form id="signIn">
                    <div class="mb-4"  style="font-size: 18px; font-weight: 600;">SignIN
                    </div>
                    <div class="form-group">
                        <div style="margin-bottom: 24px;">
                            <label class="mb-1" for="signinInputUsername">Username</label>
                            <input type="text" class="form-control" id="signinInputUsername"
                                   placeholder="Enter username">

                        </div>
                        <div style="margin-bottom: 24px;">
                            <label class="mb-1" for="signinInputPassword">Password</label>
                            <input type="password" class="form-control" id="signinInputPassword"
                                   placeholder="Enter Password">
                        </div>
                        <button type="submit" class="btn btn-primary" id="submitSignup">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script>
        $("#signUp").submit(function (event) {
            $.ajax({
                url: "{% url 'authentication:register' %}",
                method: "post",
                data: {
                    username: $("#signupInputUsername").val(),
                    first_name: $("#signupInputFirstname").val(),
                    last_name: $("#signupInputLastname").val(),
                    password: $("#signupInputPassword").val(),
                },
                headers: {
                    "X-CSRFToken": "{{ csrftoken }}"
                },
                success: function (response) {
                    window.location.replace("{% url 'game:home' %}")
                },
                error: function (response) {
                    alert("Try Again...")
                }
            });
            event.preventDefault();
        });
    </script>

    <script>
        $("#signIn").submit(function (event) {
            $.ajax({
                url: "{% url 'authentication:login' %}",
                method: "post",
                data: {
                    username: $("#signinInputUsername").val(),
                    password: $("#signinInputPassword").val(),
                },
                headers: {
                    "X-CSRFToken": "{{ csrftoken }}"
                },
                success: function (response) {
                    window.location.replace("{% url 'game:home' %}")
                },
                error: function (response) {
                    alert("Try Again...")
                }
            });
            event.preventDefault();
        });
    </script>

{% endblock %}

templates/base/base.html
{% extends "base/base_config.html" %}

{% block body %}
    <nav class="navbar navbar-expand-lg py-3 mb-4 bg-primary ">
        <div style="color: white; " class="container light justify-content-start">
            Become a Millionaire <span style="font-weight: bold">, {{ user.username }}</span>
        </div>
    </nav>
    {% block content %}{% endblock %}
{% endblock %}

templates/base/base_config.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block external_css %}
        <!-- BOOTSTRAP -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">
    {% endblock %}
    {% block internal_css %}
    {% endblock %}
    <title>
        {% block page_title %}
            Millionaire
        {% endblock %}
    </title>

</head>
<body>
{% block body %}
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
{#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"#}
{#            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"#}
{#            crossorigin="anonymous"></script>#}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}
</body>
</html>

templates/game/game-initial.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container">
        <div class="mb-3">
            <span style="font-size: 4rem">Total Score: </span>
            <span style="font-weight: bold;text-align: center;font-size: 4rem" id="score">0</span>
        </div>
        <div id="questions" class=" pb-5"
             style="display: flex; row-gap: 32px; flex-wrap: wrap;">
        </div>
        <div style="margin: 0 auto;width: 50%">
            <a href="{% url 'game:initial-template' %}"><button  class="btn-success p-4 m-5">Restart Game</button></a>
            <a href="{% url 'game:home' %}"><button class="btn-warning p-4 m-5">Go to Home</button></a>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script >
        $(document).ready(function () {
            var csrftoken = $("[name=csrfmiddlewaretoken]").val();
            $.ajax({
                url: "{%  url 'game:initial' %}",
                context: document.body,
                method: "post",
                headers: {
                    "Authorization": "Basic " + btoa("{{ user.username }}" + ":" + "{{ password }}"),
                    "X-CSRFToken": "{{ csrftoken }}"
                },
                success: function (response) {
                    for (let i = 0; i < response.data.questions.length; i++) {

                        questions = $('#questions')
                        questions.append(
                            '<div class="card col-sm-4 " style="border: none">' +
                            '<div class="px-3">' +
                            '<li class="list-group-item bg-primary" style="color: white;font-size: 1.2rem;padding: 20px">' + response.data.questions[i].text + '</li>' +
                            '<ul class="list-group list-group-flush" id=id-value>'.replace("id-value", response.data.questions[i].id) +
                            '</ul>' +
                            '</div>' +
                            '</div>'
                        );
                        for (let j = 0; j < response.data.questions[i].options.length; j++) {
                            $("#id-value".replace("id-value", response.data.questions[i].id)).append(
                                '<button onclick="answer(this)" question_id="question-id" option_id="option-id" game_uuid="game-uuid" class="answer" style="width: 100%"><li class="list-group-item">'.replace("question-id",  response.data.questions[i].id).replace("option-id", response.data.questions[i].options[j].id).replace("game-uuid", response.data.uuid)+ response.data.questions[i].options[j].text +'</li></button>'
                            )
                        }

                    }
                }
            });
        })

    </script>

    <script>
        function answer(element) {
            const question = element.getAttribute("question_id");
            const option = element.getAttribute("option_id");
            const game_uuid = element.getAttribute("game_uuid");
            $.ajax({
                url: "/game/answer/game_uuid/".replace("game_uuid", game_uuid),
                type: "post",
                headers: {
                    "Authorization": "Basic " + btoa("{{ user.username }}" + ":" + "{{ password }}"),
                    "X-CSRFToken": "{{ csrftoken }}"
                },
                data: {
                    question: parseInt(question),
                    option: parseInt(option),
                },
                success: function (response) {
                    $("[option_id=option-id]".replace("option-id", response.data.correct_answer)).css("background-color", "green");
                    $("#score").text(response.data.game_score)
                },
                error: function (response) {
                    alert("Try Again...")
                }
            });
        }
    </script>
{% endblock %}

templates/game/home.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="container">
        <div style="display: flex; justify-content: space-around">
            <div >
                <div style="width: 70%;margin: 50px auto;">
                    <p style="font-weight: bold;font-size: 6rem;margin-bottom: 20px">Do you want to be a
                        MILLIONAIRE?</p>
                    <h5 style="font-size: 4rem;font-weight: bold;margin-bottom: 20px">Give it a try</h5>
                    <a href="{% url 'game:initial-template' %}">
                        <button class="btn-danger" style="width: 50%;padding: 40px;margin: 0 auto">Start Game</button>
                    </a>
                </div>

            </div>
            <div id="topPlayersContainer">
            </div>

        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            $.ajax({
                url: "{%  url 'game:top-players' %}",
                context: document.body,
                method: "get",
                success: function (response) {
                    for (let i = 0; i < response.data.length; i++) {

                        $('#topPlayersContainer').append(
                            '<div class="card mb-2" style="border-bottom: 2px solid black; min-width: 200px;">' +
                            '<div class="card-body">' +
                            '<h5 class="card-title" style="font-size: 1rem;font-weight: bold">' + response.data[i].user.username + '</h5>' +
                            '<p class="card-text">score' + response.data[i].total_score + '</p>' +
                            '</div>' +
                            '</div >'
                        );
                    }
                }
            });
        })
    </script>
{% endblock %}